# Main ModSecurity configuration file

# Include ModSecurity core configuration
Include /etc/modsecurity/modsecurity.conf


# Include custom generated rules
Include /etc/modsec/rules/custom-rules.conf


